### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by castalonirenz** [Ehsan0Hejazi/react-native-sqlite-storage-api30#1]
<img width="750" alt="image" src="https://user-images.githubusercontent.com/13584669/166096772-3c30b5be-863b-4548-bb77-e303b03afdd2.png">

i'm encountering this one right after i uninstall the other package react-native-sqlite-storage

**Comment by Ehsan0Hejazi** [comment]
ok I think I found the problem
just follow this

in react-native.config.js

your dependencies should be as follows

```
dependencies: {
      "react-native-sqlite-storage-api30": {
        platforms: {
          android: {
            sourceDir:
              "../node_modules/react-native-sqlite-storage-api30/platforms/android-native",
            packageImportPath: "import io.liteglue.SQLitePluginPackage;",
            packageInstance: "new SQLitePluginPackage()"
          }
        }
      }
    }
```

you are exporting "react-native-sqlite-storage" while you need to export "react-native-sqlite-storage-api30"

let me know if your problem is solved

**Comment by castalonirenz** [comment]
> ok I think I found the problem just follow this
> 
> in react-native.config.js
> 
> your dependencies should be as follows
> 
> ```
> dependencies: {
>       "react-native-sqlite-storage-api30": {
>         platforms: {
>           android: {
>             sourceDir:
>               "../node_modules/react-native-sqlite-storage-api30/platforms/android-native",
>             packageImportPath: "import io.liteglue.SQLitePluginPackage;",
>             packageInstance: "new SQLitePluginPackage()"
>           }
>         }
>       }
>     }
> ```
> 
> you are exporting "react-native-sqlite-storage" while you need to export "react-native-sqlite-storage-api30"
> 
> let me know if your problem is solved


Sorry for that one i overlooked it but now i successfully buil it but the app crashes right after calling the SQLite function

<img width="882" alt="image" src="https://user-images.githubusercontent.com/13584669/166102441-464faf16-c08b-486c-80e1-bd703565b2bd.png">

**Comment by Ehsan0Hejazi** [comment]
This library is working for me correctly,
Could you please show me the line you imported SQLite?

**Comment by castalonirenz** [comment]
<img width="296" alt="image" src="https://user-images.githubusercontent.com/13584669/166103310-0d095a07-ef05-456c-998e-24430c31cd9b.png">

<img width="640" alt="image" src="https://user-images.githubusercontent.com/13584669/166103320-99c179c4-db17-4bbb-962b-e64bea81c5b7.png">

**Comment by castalonirenz** [comment]
@Ehsan0Hejazi Can you share your build gradle? And what react-native version are you using? Mine is 0.64

**Comment by Ehsan0Hejazi** [comment]
build.gradle

```
buildscript {
    ext {
        buildToolsVersion = "30.0.3"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        ndkVersion = "20.1.5948944"
        googlePlayServicesAuthVersion = "19.2.0" // <--- use this version or newer
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:4.2.1")
        classpath 'com.google.gms:google-services:4.3.10'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.8.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenCentral()
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        maven { url 'https://www.jitpack.io' }
    }
}
```

RN : 0.65.1

**Comment by castalonirenz** [comment]
We are almost the same build gradle. I dont know whats causing the crash.

**Comment by castalonirenz** [comment]
I will try to generate a fresh new project and try this package will get back to you on monday thanks for your response @Ehsan0Hejazi  i appreciate it.

**Comment by Ehsan0Hejazi** [comment]
I can confirm package in working in production with no problem,
please let me know asap,

Have a nice day,

**Comment by castalonirenz** [comment]
I created a fresh project i encounter this

    "react-native": "0.68.1"


<img width="553" alt="image" src="https://user-images.githubusercontent.com/13584669/166183383-2259d569-be97-407d-bbab-4d143216898f.png">

<img width="476" alt="image" src="https://user-images.githubusercontent.com/13584669/166183464-77c68485-4262-45be-9ec5-cfd28012a65b.png">

latest react native version

**Comment by castalonirenz** [comment]
this is now working on my end

**Comment by bwmarrin** [comment]
@castalonirenz 

> > ok I think I found the problem just follow this
> > in react-native.config.js
> > your dependencies should be as follows
> > ```
> > dependencies: {
> >       "react-native-sqlite-storage-api30": {
> >         platforms: {
> >           android: {
> >             sourceDir:
> >               "../node_modules/react-native-sqlite-storage-api30/platforms/android-native",
> >             packageImportPath: "import io.liteglue.SQLitePluginPackage;",
> >             packageInstance: "new SQLitePluginPackage()"
> >           }
> >         }
> >       }
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > you are exporting "react-native-sqlite-storage" while you need to export "react-native-sqlite-storage-api30"
> > let me know if your problem is solved
> 
> Sorry for that one i overlooked it but now i successfully buil it but the app crashes right after calling the SQLite function
> 
> <img alt="image" width="882" src="https://user-images.githubusercontent.com/13584669/166102441-464faf16-c08b-486c-80e1-bd703565b2bd.png">


I'm running into this same error and am wondering what you did to resolve this?

```
2022-10-03 11:01:01.927 26878-26937/? runtime.cc:638] JNI DETECTED ERROR IN APPLICATION: mid == null
2022-10-03 11:01:02.072 26943-26943/? A/DEBUG: Abort message: 'JNI DETECTED ERROR IN APPLICATION: mid == null
        in call to NewObject
        from io.liteglue.SQLiteResponse io.liteglue.SQLiteNative.sqlc_db_open(java.lang.String, int)
```
